version: "3.8"

services:
  fastapi_app:
    image: python:3.9-slim
    container_name: Stash-Tracker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        pip install --no-cache-dir -r requirements.txt &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqlite-db
    volumes:
      - ./stash_tracker.db:/app/stash_tracker.db
    environment:
      - SQLITE_DATABASE_FILE=/app/stash_tracker.db
