version: "3.8"

services:
  fastapi_app:
    image: python:3.9-slim
    container_name: Stash-Tracker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        pip install --no-cache-dir -r requirements.txt &&
        python main.py
      "
    environment:
      - PYTHONUNBUFFERED=1